on: [push]

name: Upload Release Asset
jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binaries
        run: GOOS=linux GOARCH=amd64 go build -o dyndns

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dyndns
          path: ./dyndns
